general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

window.opacity = 0.55

[env]
TERM = "xterm-256color"

[font]
normal.family = "Space Mono"
bold.family = "Space Mono"
italic.family = "Space Mono"
bold_italic.family = "Space Mono"

size = 14.25
